name: Build and deploy PHP app to Azure Web App - artic-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: artic-backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
